name: Generate API Spec HTML (Redoc)

on:
  push:
    branches:
      - main
      - develop
    paths:
      - '.github/workflows/redoc-openapi.yml'
      - 'openapi.yaml'

jobs:
  generate-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - name: Install Redocly CLI
        run: npm i -g @redocly/cli@latest
      - name: Generate HTML
        run: |
          mkdir -p dist
          redocly build-docs openapi.yaml -o dist/api-spec.html
      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: api-spec-html
          path: |
            dist/api-spec.html
      - uses: actions/checkout@v4
        with:
          ref: gh-pages
      - uses: actions/download-artifact@v3
        with:
          name: api-spec-html
          path: /tmp/docs/
      - name: Push to gh-pages
        run: |
          mkdir -p docs
          cp /tmp/docs/api-spec.html docs/api-spec.html
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          
          # 変更があった場合のみ push
          git add docs/api-spec.html && git diff --cached --exit-code --quiet || \
            git commit -m "Update docs/api-spec.html" && git push origin HEAD
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}